version: "3.8"
services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: PERSONA
      MYSQL_USER: STEPUP
      MYSQL_PASSWORD: "!stepup@persona#301"
      MYSQL_ROOT_PASSWORD: "!stepup@persona#301"
      MYSQL_VERSION: "8.0.31"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - my-db-data:/var/lib/mysql
volumes:
  my-db-data:
