version: "3.8"
services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password --initialize-insecure # 수정된 부분
    restart: always
    environment:
      MYSQL_DATABASE: PERSONA
      MYSQL_USER: STEPUP
      MYSQL_PASSWORD: "!stepup@persona#301"
      MYSQL_ROOT_PASSWORD: "!stepup@persona#301"
    ports:
      - "3306:3306"
    #volumes:
    #  - ./db-data:/var/lib/mysql

