version: "3.8"
services:
  app:
    build: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: PERSONA
      MYSQL_USER: STEPUP
      MYSQL_PASSWORD: "!stepup@persona#301"
      MYSQL_ROOT_PASSWORD: "!stepup@persona#301"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql/data
volumes:
  db-data:
