version: "3.8"
services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c 'while ! mysqladmin ping -hdb --silent; do echo "Waiting for MySQL..."; sleep 1; done; java -jar my-app.jar'
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: PERSONA
      MYSQL_USER: STEPUP
      MYSQL_PASSWORD: "!stepup@persona#301"
      MYSQL_ROOT_PASSWORD: "!stepup@persona#301"
      MYSQL_VERSION: "8.0.31"
    ports:
      - "3306:3306"
    volumes:
      - my-db-data:/var/lib/mysql
volumes:
  my-db-data:
