server:
  servlet:
    context-path:
    port: ${server.port}


logging:
  config: classpath:log4j2.xml


spring:


  profiles:
    include: env, app


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.id}
            client-pwd: ${oauth2.google.pwd}
            scope:
              - openid
              - email


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.port}/test?allowPublicKeyRetrieval=true&useSSL=false&useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${mysql.user}
    password: ${mysql.pwd}


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#  redis:
#    host: ${redis.host}
#    port: ${redis.port}
#    password: ${redis.pwd}

  servlet:
    multipart:
      max-file-size: 1000000MB
      max-request-size: 1000000MB