app:
  oauth2:
    authorized-redirect-uris: http://localhost:8080/oauth2/callback/google

  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000

server:
  port: 8080

mysql:
  port: localhost:3306
  user: root
  pwd: ssafy

redis:
  host: localhost
  port: 6379
  pwd:

oauth2:
  google:
    id: 210492167110-lfiuso34ko9chdv1qvkh39hefeh8gugv.apps.googleusercontent.com
    secret: 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


cors:
  allowedOrigins: http://localhost:3000